// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eater.proto

package eater

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EaterProfile struct {
	EaterId                string   `protobuf:"bytes,1,opt,name=eater_id,proto3" json:"eater_id,omitempty"`
	PhoneNumber            string   `protobuf:"bytes,2,opt,name=phone_number,proto3" json:"phone_number,omitempty"`
	Name                   string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IsPhoneNumberConfirmed bool     `protobuf:"varint,4,opt,name=is_phone_number_confirmed,proto3" json:"is_phone_number_confirmed,omitempty"`
	CreatedAt              string   `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt              string   `protobuf:"bytes,6,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *EaterProfile) Reset()         { *m = EaterProfile{} }
func (m *EaterProfile) String() string { return proto.CompactTextString(m) }
func (*EaterProfile) ProtoMessage()    {}
func (*EaterProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6f01ea7777882c2, []int{0}
}

func (m *EaterProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EaterProfile.Unmarshal(m, b)
}
func (m *EaterProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EaterProfile.Marshal(b, m, deterministic)
}
func (m *EaterProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EaterProfile.Merge(m, src)
}
func (m *EaterProfile) XXX_Size() int {
	return xxx_messageInfo_EaterProfile.Size(m)
}
func (m *EaterProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_EaterProfile.DiscardUnknown(m)
}

var xxx_messageInfo_EaterProfile proto.InternalMessageInfo

func (m *EaterProfile) GetEaterId() string {
	if m != nil {
		return m.EaterId
	}
	return ""
}

func (m *EaterProfile) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *EaterProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EaterProfile) GetIsPhoneNumberConfirmed() bool {
	if m != nil {
		return m.IsPhoneNumberConfirmed
	}
	return false
}

func (m *EaterProfile) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *EaterProfile) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type SignupEaterRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupEaterRequest) Reset()         { *m = SignupEaterRequest{} }
func (m *SignupEaterRequest) String() string { return proto.CompactTextString(m) }
func (*SignupEaterRequest) ProtoMessage()    {}
func (*SignupEaterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6f01ea7777882c2, []int{1}
}

func (m *SignupEaterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupEaterRequest.Unmarshal(m, b)
}
func (m *SignupEaterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupEaterRequest.Marshal(b, m, deterministic)
}
func (m *SignupEaterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupEaterRequest.Merge(m, src)
}
func (m *SignupEaterRequest) XXX_Size() int {
	return xxx_messageInfo_SignupEaterRequest.Size(m)
}
func (m *SignupEaterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupEaterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupEaterRequest proto.InternalMessageInfo

func (m *SignupEaterRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type SignupEaterResponse struct {
	EaterId              string   `protobuf:"bytes,1,opt,name=eater_id,proto3" json:"eater_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupEaterResponse) Reset()         { *m = SignupEaterResponse{} }
func (m *SignupEaterResponse) String() string { return proto.CompactTextString(m) }
func (*SignupEaterResponse) ProtoMessage()    {}
func (*SignupEaterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6f01ea7777882c2, []int{2}
}

func (m *SignupEaterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupEaterResponse.Unmarshal(m, b)
}
func (m *SignupEaterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupEaterResponse.Marshal(b, m, deterministic)
}
func (m *SignupEaterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupEaterResponse.Merge(m, src)
}
func (m *SignupEaterResponse) XXX_Size() int {
	return xxx_messageInfo_SignupEaterResponse.Size(m)
}
func (m *SignupEaterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupEaterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignupEaterResponse proto.InternalMessageInfo

func (m *SignupEaterResponse) GetEaterId() string {
	if m != nil {
		return m.EaterId
	}
	return ""
}

type ConfirmSmsCodeRequest struct {
	EaterId              string   `protobuf:"bytes,1,opt,name=eater_id,json=eaterId,proto3" json:"eater_id,omitempty"`
	SmsCode              string   `protobuf:"bytes,2,opt,name=sms_code,json=smsCode,proto3" json:"sms_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmSmsCodeRequest) Reset()         { *m = ConfirmSmsCodeRequest{} }
func (m *ConfirmSmsCodeRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmSmsCodeRequest) ProtoMessage()    {}
func (*ConfirmSmsCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6f01ea7777882c2, []int{3}
}

func (m *ConfirmSmsCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmSmsCodeRequest.Unmarshal(m, b)
}
func (m *ConfirmSmsCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmSmsCodeRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmSmsCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmSmsCodeRequest.Merge(m, src)
}
func (m *ConfirmSmsCodeRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmSmsCodeRequest.Size(m)
}
func (m *ConfirmSmsCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmSmsCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmSmsCodeRequest proto.InternalMessageInfo

func (m *ConfirmSmsCodeRequest) GetEaterId() string {
	if m != nil {
		return m.EaterId
	}
	return ""
}

func (m *ConfirmSmsCodeRequest) GetSmsCode() string {
	if m != nil {
		return m.SmsCode
	}
	return ""
}

type ConfirmSmsCodeResponse struct {
	Profile              *EaterProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Token                string        `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ConfirmSmsCodeResponse) Reset()         { *m = ConfirmSmsCodeResponse{} }
func (m *ConfirmSmsCodeResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmSmsCodeResponse) ProtoMessage()    {}
func (*ConfirmSmsCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6f01ea7777882c2, []int{4}
}

func (m *ConfirmSmsCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmSmsCodeResponse.Unmarshal(m, b)
}
func (m *ConfirmSmsCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmSmsCodeResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmSmsCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmSmsCodeResponse.Merge(m, src)
}
func (m *ConfirmSmsCodeResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmSmsCodeResponse.Size(m)
}
func (m *ConfirmSmsCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmSmsCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmSmsCodeResponse proto.InternalMessageInfo

func (m *ConfirmSmsCodeResponse) GetProfile() *EaterProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *ConfirmSmsCodeResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UpdateEaterProfileRequest struct {
	EaterId              string   `protobuf:"bytes,1,opt,name=eater_id,proto3" json:"eater_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl             string   `protobuf:"bytes,3,opt,name=image_url,proto3" json:"image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEaterProfileRequest) Reset()         { *m = UpdateEaterProfileRequest{} }
func (m *UpdateEaterProfileRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEaterProfileRequest) ProtoMessage()    {}
func (*UpdateEaterProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6f01ea7777882c2, []int{5}
}

func (m *UpdateEaterProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEaterProfileRequest.Unmarshal(m, b)
}
func (m *UpdateEaterProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEaterProfileRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEaterProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEaterProfileRequest.Merge(m, src)
}
func (m *UpdateEaterProfileRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEaterProfileRequest.Size(m)
}
func (m *UpdateEaterProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEaterProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEaterProfileRequest proto.InternalMessageInfo

func (m *UpdateEaterProfileRequest) GetEaterId() string {
	if m != nil {
		return m.EaterId
	}
	return ""
}

func (m *UpdateEaterProfileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateEaterProfileRequest) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type UpdateEaterProfileResponse struct {
	Profile              *EaterProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateEaterProfileResponse) Reset()         { *m = UpdateEaterProfileResponse{} }
func (m *UpdateEaterProfileResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateEaterProfileResponse) ProtoMessage()    {}
func (*UpdateEaterProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6f01ea7777882c2, []int{6}
}

func (m *UpdateEaterProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEaterProfileResponse.Unmarshal(m, b)
}
func (m *UpdateEaterProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEaterProfileResponse.Marshal(b, m, deterministic)
}
func (m *UpdateEaterProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEaterProfileResponse.Merge(m, src)
}
func (m *UpdateEaterProfileResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateEaterProfileResponse.Size(m)
}
func (m *UpdateEaterProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEaterProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEaterProfileResponse proto.InternalMessageInfo

func (m *UpdateEaterProfileResponse) GetProfile() *EaterProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type GetEaterProfileRequest struct {
	EaterId              string   `protobuf:"bytes,1,opt,name=eater_id,json=eaterId,proto3" json:"eater_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEaterProfileRequest) Reset()         { *m = GetEaterProfileRequest{} }
func (m *GetEaterProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetEaterProfileRequest) ProtoMessage()    {}
func (*GetEaterProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6f01ea7777882c2, []int{7}
}

func (m *GetEaterProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEaterProfileRequest.Unmarshal(m, b)
}
func (m *GetEaterProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEaterProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetEaterProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEaterProfileRequest.Merge(m, src)
}
func (m *GetEaterProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetEaterProfileRequest.Size(m)
}
func (m *GetEaterProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEaterProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEaterProfileRequest proto.InternalMessageInfo

func (m *GetEaterProfileRequest) GetEaterId() string {
	if m != nil {
		return m.EaterId
	}
	return ""
}

type GetEaterProfileResponse struct {
	Profile              *EaterProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetEaterProfileResponse) Reset()         { *m = GetEaterProfileResponse{} }
func (m *GetEaterProfileResponse) String() string { return proto.CompactTextString(m) }
func (*GetEaterProfileResponse) ProtoMessage()    {}
func (*GetEaterProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6f01ea7777882c2, []int{8}
}

func (m *GetEaterProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEaterProfileResponse.Unmarshal(m, b)
}
func (m *GetEaterProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEaterProfileResponse.Marshal(b, m, deterministic)
}
func (m *GetEaterProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEaterProfileResponse.Merge(m, src)
}
func (m *GetEaterProfileResponse) XXX_Size() int {
	return xxx_messageInfo_GetEaterProfileResponse.Size(m)
}
func (m *GetEaterProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEaterProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEaterProfileResponse proto.InternalMessageInfo

func (m *GetEaterProfileResponse) GetProfile() *EaterProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func init() {
	proto.RegisterType((*EaterProfile)(nil), "EaterProfile")
	proto.RegisterType((*SignupEaterRequest)(nil), "SignupEaterRequest")
	proto.RegisterType((*SignupEaterResponse)(nil), "SignupEaterResponse")
	proto.RegisterType((*ConfirmSmsCodeRequest)(nil), "ConfirmSmsCodeRequest")
	proto.RegisterType((*ConfirmSmsCodeResponse)(nil), "ConfirmSmsCodeResponse")
	proto.RegisterType((*UpdateEaterProfileRequest)(nil), "UpdateEaterProfileRequest")
	proto.RegisterType((*UpdateEaterProfileResponse)(nil), "UpdateEaterProfileResponse")
	proto.RegisterType((*GetEaterProfileRequest)(nil), "GetEaterProfileRequest")
	proto.RegisterType((*GetEaterProfileResponse)(nil), "GetEaterProfileResponse")
}

func init() { proto.RegisterFile("eater.proto", fileDescriptor_d6f01ea7777882c2) }

var fileDescriptor_d6f01ea7777882c2 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4f, 0x4f, 0xfa, 0x40,
	0x10, 0x4d, 0xf9, 0x01, 0x85, 0x81, 0xdf, 0x65, 0x55, 0x2c, 0xc4, 0x18, 0xdc, 0x8b, 0x9c, 0x30,
	0xca, 0xc1, 0x8b, 0x27, 0x08, 0x31, 0x1e, 0x34, 0xa6, 0xc4, 0x98, 0x78, 0x69, 0x0a, 0x3b, 0xe0,
	0x46, 0xba, 0x5b, 0x77, 0xdb, 0xef, 0xeb, 0x47, 0x31, 0xdd, 0xb6, 0x52, 0xfe, 0x26, 0xdc, 0x98,
	0xf7, 0x76, 0xde, 0xbc, 0x99, 0x47, 0xa1, 0x81, 0x7e, 0x84, 0xaa, 0x1f, 0x2a, 0x19, 0x49, 0xfa,
	0x63, 0x41, 0x73, 0x9c, 0xd4, 0xaf, 0x4a, 0xce, 0xf9, 0x12, 0x49, 0x07, 0x6a, 0x86, 0xf7, 0x38,
	0x73, 0xac, 0xae, 0xd5, 0xab, 0xbb, 0x7f, 0x35, 0xa1, 0xd0, 0x0c, 0x3f, 0xa5, 0x40, 0x4f, 0xc4,
	0xc1, 0x14, 0x95, 0x53, 0x32, 0xfc, 0x1a, 0x46, 0x08, 0x94, 0x85, 0x1f, 0xa0, 0xf3, 0xcf, 0x70,
	0xe6, 0x37, 0x79, 0x80, 0x36, 0xd7, 0x5e, 0xf1, 0x99, 0x37, 0x93, 0x62, 0xce, 0x55, 0x80, 0xcc,
	0x29, 0x77, 0xad, 0x5e, 0xcd, 0xdd, 0xff, 0x80, 0x5c, 0x02, 0xcc, 0x54, 0xe2, 0x81, 0x79, 0x7e,
	0xe4, 0x54, 0x8c, 0x6e, 0x01, 0x49, 0xf8, 0x38, 0x64, 0x39, 0x5f, 0x4d, 0xf9, 0x15, 0x42, 0xef,
	0x81, 0x4c, 0xf8, 0x42, 0xc4, 0xa1, 0xd9, 0xd3, 0xc5, 0xef, 0x18, 0x75, 0x44, 0xae, 0x36, 0x76,
	0x49, 0x77, 0x6d, 0x18, 0xec, 0xc5, 0x40, 0xf4, 0x16, 0x4e, 0xd6, 0x1a, 0x75, 0x28, 0x85, 0x3e,
	0x78, 0x21, 0xfa, 0x0c, 0x67, 0xa3, 0xd4, 0xf8, 0x24, 0xd0, 0x23, 0xc9, 0x30, 0x1f, 0xd7, 0xde,
	0x6a, 0xb2, 0x4d, 0xfd, 0xc4, 0x12, 0x4a, 0x07, 0xda, 0x9b, 0x49, 0x86, 0xd9, 0x45, 0x6d, 0x9d,
	0x36, 0xd3, 0x77, 0x68, 0x6d, 0xca, 0x65, 0x26, 0xae, 0xc1, 0x0e, 0xd3, 0xc4, 0x8c, 0x5c, 0xe3,
	0xee, 0x7f, 0xbf, 0x18, 0xa3, 0x9b, 0xb3, 0xe4, 0x14, 0x2a, 0x91, 0xfc, 0x42, 0x91, 0x49, 0xa7,
	0x05, 0xe5, 0xd0, 0x7e, 0x33, 0x17, 0x5a, 0x6b, 0xca, 0xbc, 0x1e, 0xfa, 0x0b, 0xe4, 0xf1, 0x96,
	0x0a, 0xf1, 0x5e, 0x40, 0x9d, 0x07, 0xfe, 0x02, 0xbd, 0x58, 0x2d, 0xb3, 0xdc, 0x57, 0x00, 0x1d,
	0x43, 0x67, 0xd7, 0xa8, 0x23, 0xf7, 0xa0, 0x03, 0x68, 0x3d, 0x62, 0xb4, 0xcb, 0xee, 0xfe, 0xd3,
	0xd2, 0x21, 0x9c, 0x6f, 0x35, 0x1d, 0x39, 0x78, 0x58, 0xff, 0xb0, 0xfb, 0x37, 0x46, 0x70, 0x5a,
	0x35, 0xdf, 0xcc, 0xe0, 0x37, 0x00, 0x00, 0xff, 0xff, 0x07, 0xc8, 0x03, 0x3f, 0x42, 0x03, 0x00,
	0x00,
}
