// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package eater

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RestaurantInfo struct {
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl             string   `protobuf:"bytes,4,opt,name=image_url,proto3" json:"image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestaurantInfo) Reset()         { *m = RestaurantInfo{} }
func (m *RestaurantInfo) String() string { return proto.CompactTextString(m) }
func (*RestaurantInfo) ProtoMessage()    {}
func (*RestaurantInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *RestaurantInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestaurantInfo.Unmarshal(m, b)
}
func (m *RestaurantInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestaurantInfo.Marshal(b, m, deterministic)
}
func (m *RestaurantInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestaurantInfo.Merge(m, src)
}
func (m *RestaurantInfo) XXX_Size() int {
	return xxx_messageInfo_RestaurantInfo.Size(m)
}
func (m *RestaurantInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RestaurantInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RestaurantInfo proto.InternalMessageInfo

func (m *RestaurantInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RestaurantInfo) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type AddressInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Longitude            float64  `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float64  `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressInfo) Reset()         { *m = AddressInfo{} }
func (m *AddressInfo) String() string { return proto.CompactTextString(m) }
func (*AddressInfo) ProtoMessage()    {}
func (*AddressInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *AddressInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressInfo.Unmarshal(m, b)
}
func (m *AddressInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressInfo.Marshal(b, m, deterministic)
}
func (m *AddressInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressInfo.Merge(m, src)
}
func (m *AddressInfo) XXX_Size() int {
	return xxx_messageInfo_AddressInfo.Size(m)
}
func (m *AddressInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AddressInfo proto.InternalMessageInfo

func (m *AddressInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddressInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddressInfo) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *AddressInfo) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

type DeliveryInfo struct {
	Address              *AddressInfo `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Time                 string       `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Notes                string       `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DeliveryInfo) Reset()         { *m = DeliveryInfo{} }
func (m *DeliveryInfo) String() string { return proto.CompactTextString(m) }
func (*DeliveryInfo) ProtoMessage()    {}
func (*DeliveryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *DeliveryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliveryInfo.Unmarshal(m, b)
}
func (m *DeliveryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliveryInfo.Marshal(b, m, deterministic)
}
func (m *DeliveryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliveryInfo.Merge(m, src)
}
func (m *DeliveryInfo) XXX_Size() int {
	return xxx_messageInfo_DeliveryInfo.Size(m)
}
func (m *DeliveryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliveryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeliveryInfo proto.InternalMessageInfo

func (m *DeliveryInfo) GetAddress() *AddressInfo {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *DeliveryInfo) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *DeliveryInfo) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

type PaymentInfo struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	CardId               string   `protobuf:"bytes,2,opt,name=card_id,proto3" json:"card_id,omitempty"`
	DeliveryPrice        int32    `protobuf:"varint,3,opt,name=delivery_price,proto3" json:"delivery_price,omitempty"`
	TotalPrice           int32    `protobuf:"varint,4,opt,name=total_price,proto3" json:"total_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentInfo) Reset()         { *m = PaymentInfo{} }
func (m *PaymentInfo) String() string { return proto.CompactTextString(m) }
func (*PaymentInfo) ProtoMessage()    {}
func (*PaymentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *PaymentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentInfo.Unmarshal(m, b)
}
func (m *PaymentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentInfo.Marshal(b, m, deterministic)
}
func (m *PaymentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentInfo.Merge(m, src)
}
func (m *PaymentInfo) XXX_Size() int {
	return xxx_messageInfo_PaymentInfo.Size(m)
}
func (m *PaymentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentInfo proto.InternalMessageInfo

func (m *PaymentInfo) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *PaymentInfo) GetCardId() string {
	if m != nil {
		return m.CardId
	}
	return ""
}

func (m *PaymentInfo) GetDeliveryPrice() int32 {
	if m != nil {
		return m.DeliveryPrice
	}
	return 0
}

func (m *PaymentInfo) GetTotalPrice() int32 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

type CartProduct struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                int32    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CartProduct) Reset()         { *m = CartProduct{} }
func (m *CartProduct) String() string { return proto.CompactTextString(m) }
func (*CartProduct) ProtoMessage()    {}
func (*CartProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *CartProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartProduct.Unmarshal(m, b)
}
func (m *CartProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartProduct.Marshal(b, m, deterministic)
}
func (m *CartProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartProduct.Merge(m, src)
}
func (m *CartProduct) XXX_Size() int {
	return xxx_messageInfo_CartProduct.Size(m)
}
func (m *CartProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_CartProduct.DiscardUnknown(m)
}

var xxx_messageInfo_CartProduct proto.InternalMessageInfo

func (m *CartProduct) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CartProduct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CartProduct) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type CartItem struct {
	Product              *CartProduct `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Quantity             int32        `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CartItem) Reset()         { *m = CartItem{} }
func (m *CartItem) String() string { return proto.CompactTextString(m) }
func (*CartItem) ProtoMessage()    {}
func (*CartItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{5}
}

func (m *CartItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartItem.Unmarshal(m, b)
}
func (m *CartItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartItem.Marshal(b, m, deterministic)
}
func (m *CartItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartItem.Merge(m, src)
}
func (m *CartItem) XXX_Size() int {
	return xxx_messageInfo_CartItem.Size(m)
}
func (m *CartItem) XXX_DiscardUnknown() {
	xxx_messageInfo_CartItem.DiscardUnknown(m)
}

var xxx_messageInfo_CartItem proto.InternalMessageInfo

func (m *CartItem) GetProduct() *CartProduct {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *CartItem) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type Cart struct {
	Instruction          string          `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	Restaurant           *RestaurantInfo `protobuf:"bytes,2,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	Delivery             *DeliveryInfo   `protobuf:"bytes,3,opt,name=delivery,proto3" json:"delivery,omitempty"`
	Payment              *PaymentInfo    `protobuf:"bytes,4,opt,name=payment,proto3" json:"payment,omitempty"`
	Items                []*CartItem     `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Cart) Reset()         { *m = Cart{} }
func (m *Cart) String() string { return proto.CompactTextString(m) }
func (*Cart) ProtoMessage()    {}
func (*Cart) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{6}
}

func (m *Cart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cart.Unmarshal(m, b)
}
func (m *Cart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cart.Marshal(b, m, deterministic)
}
func (m *Cart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cart.Merge(m, src)
}
func (m *Cart) XXX_Size() int {
	return xxx_messageInfo_Cart.Size(m)
}
func (m *Cart) XXX_DiscardUnknown() {
	xxx_messageInfo_Cart.DiscardUnknown(m)
}

var xxx_messageInfo_Cart proto.InternalMessageInfo

func (m *Cart) GetInstruction() string {
	if m != nil {
		return m.Instruction
	}
	return ""
}

func (m *Cart) GetRestaurant() *RestaurantInfo {
	if m != nil {
		return m.Restaurant
	}
	return nil
}

func (m *Cart) GetDelivery() *DeliveryInfo {
	if m != nil {
		return m.Delivery
	}
	return nil
}

func (m *Cart) GetPayment() *PaymentInfo {
	if m != nil {
		return m.Payment
	}
	return nil
}

func (m *Cart) GetItems() []*CartItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type OrderItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,proto3" json:"product_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Quantity             int32    `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                int32    `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	TotalPrice           int32    `protobuf:"varint,6,opt,name=total_price,proto3" json:"total_price,omitempty"`
	CreatedAt            string   `protobuf:"bytes,7,opt,name=created_at,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderItem) Reset()         { *m = OrderItem{} }
func (m *OrderItem) String() string { return proto.CompactTextString(m) }
func (*OrderItem) ProtoMessage()    {}
func (*OrderItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{7}
}

func (m *OrderItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderItem.Unmarshal(m, b)
}
func (m *OrderItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderItem.Marshal(b, m, deterministic)
}
func (m *OrderItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderItem.Merge(m, src)
}
func (m *OrderItem) XXX_Size() int {
	return xxx_messageInfo_OrderItem.Size(m)
}
func (m *OrderItem) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderItem.DiscardUnknown(m)
}

var xxx_messageInfo_OrderItem proto.InternalMessageInfo

func (m *OrderItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderItem) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *OrderItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrderItem) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *OrderItem) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderItem) GetTotalPrice() int32 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *OrderItem) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type Order struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EaterId              string          `protobuf:"bytes,2,opt,name=eater_id,proto3" json:"eater_id,omitempty"`
	Instruction          string          `protobuf:"bytes,3,opt,name=instruction,proto3" json:"instruction,omitempty"`
	EntityId             string          `protobuf:"bytes,4,opt,name=entity_id,proto3" json:"entity_id,omitempty"`
	Restaurant           *RestaurantInfo `protobuf:"bytes,5,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	Delivery             *DeliveryInfo   `protobuf:"bytes,6,opt,name=delivery,proto3" json:"delivery,omitempty"`
	Payment              *PaymentInfo    `protobuf:"bytes,7,opt,name=payment,proto3" json:"payment,omitempty"`
	Items                []*OrderItem    `protobuf:"bytes,8,rep,name=items,proto3" json:"items,omitempty"`
	Status               string          `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	PaymentStatus        string          `protobuf:"bytes,10,opt,name=payment_status,proto3" json:"payment_status,omitempty"`
	CreatedAt            string          `protobuf:"bytes,11,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt            string          `protobuf:"bytes,12,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{8}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetEaterId() string {
	if m != nil {
		return m.EaterId
	}
	return ""
}

func (m *Order) GetInstruction() string {
	if m != nil {
		return m.Instruction
	}
	return ""
}

func (m *Order) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *Order) GetRestaurant() *RestaurantInfo {
	if m != nil {
		return m.Restaurant
	}
	return nil
}

func (m *Order) GetDelivery() *DeliveryInfo {
	if m != nil {
		return m.Delivery
	}
	return nil
}

func (m *Order) GetPayment() *PaymentInfo {
	if m != nil {
		return m.Payment
	}
	return nil
}

func (m *Order) GetItems() []*OrderItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetPaymentStatus() string {
	if m != nil {
		return m.PaymentStatus
	}
	return ""
}

func (m *Order) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Order) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type PlaceOrderRequest struct {
	EaterId              string   `protobuf:"bytes,1,opt,name=eater_id,proto3" json:"eater_id,omitempty"`
	RestaurantId         string   `protobuf:"bytes,2,opt,name=restaurant_id,proto3" json:"restaurant_id,omitempty"`
	Instruction          string   `protobuf:"bytes,3,opt,name=instruction,proto3" json:"instruction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceOrderRequest) Reset()         { *m = PlaceOrderRequest{} }
func (m *PlaceOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PlaceOrderRequest) ProtoMessage()    {}
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{9}
}

func (m *PlaceOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceOrderRequest.Unmarshal(m, b)
}
func (m *PlaceOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceOrderRequest.Marshal(b, m, deterministic)
}
func (m *PlaceOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceOrderRequest.Merge(m, src)
}
func (m *PlaceOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PlaceOrderRequest.Size(m)
}
func (m *PlaceOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceOrderRequest proto.InternalMessageInfo

func (m *PlaceOrderRequest) GetEaterId() string {
	if m != nil {
		return m.EaterId
	}
	return ""
}

func (m *PlaceOrderRequest) GetRestaurantId() string {
	if m != nil {
		return m.RestaurantId
	}
	return ""
}

func (m *PlaceOrderRequest) GetInstruction() string {
	if m != nil {
		return m.Instruction
	}
	return ""
}

type PlaceOrderResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceOrderResponse) Reset()         { *m = PlaceOrderResponse{} }
func (m *PlaceOrderResponse) String() string { return proto.CompactTextString(m) }
func (*PlaceOrderResponse) ProtoMessage()    {}
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{10}
}

func (m *PlaceOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceOrderResponse.Unmarshal(m, b)
}
func (m *PlaceOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceOrderResponse.Marshal(b, m, deterministic)
}
func (m *PlaceOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceOrderResponse.Merge(m, src)
}
func (m *PlaceOrderResponse) XXX_Size() int {
	return xxx_messageInfo_PlaceOrderResponse.Size(m)
}
func (m *PlaceOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceOrderResponse proto.InternalMessageInfo

func (m *PlaceOrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type UpdateOrderRequest struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOrderRequest) Reset()         { *m = UpdateOrderRequest{} }
func (m *UpdateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateOrderRequest) ProtoMessage()    {}
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{11}
}

func (m *UpdateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrderRequest.Unmarshal(m, b)
}
func (m *UpdateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrderRequest.Marshal(b, m, deterministic)
}
func (m *UpdateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrderRequest.Merge(m, src)
}
func (m *UpdateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateOrderRequest.Size(m)
}
func (m *UpdateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrderRequest proto.InternalMessageInfo

func (m *UpdateOrderRequest) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type UpdateOrderResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOrderResponse) Reset()         { *m = UpdateOrderResponse{} }
func (m *UpdateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateOrderResponse) ProtoMessage()    {}
func (*UpdateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{12}
}

func (m *UpdateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrderResponse.Unmarshal(m, b)
}
func (m *UpdateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrderResponse.Marshal(b, m, deterministic)
}
func (m *UpdateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrderResponse.Merge(m, src)
}
func (m *UpdateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateOrderResponse.Size(m)
}
func (m *UpdateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrderResponse proto.InternalMessageInfo

func (m *UpdateOrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type GetOrderRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderRequest) Reset()         { *m = GetOrderRequest{} }
func (m *GetOrderRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderRequest) ProtoMessage()    {}
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{13}
}

func (m *GetOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderRequest.Unmarshal(m, b)
}
func (m *GetOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderRequest.Merge(m, src)
}
func (m *GetOrderRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderRequest.Size(m)
}
func (m *GetOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderRequest proto.InternalMessageInfo

func (m *GetOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type GetOrderResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderResponse) Reset()         { *m = GetOrderResponse{} }
func (m *GetOrderResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrderResponse) ProtoMessage()    {}
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{14}
}

func (m *GetOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderResponse.Unmarshal(m, b)
}
func (m *GetOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderResponse.Marshal(b, m, deterministic)
}
func (m *GetOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderResponse.Merge(m, src)
}
func (m *GetOrderResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrderResponse.Size(m)
}
func (m *GetOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderResponse proto.InternalMessageInfo

func (m *GetOrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type DeleteOrderRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOrderRequest) Reset()         { *m = DeleteOrderRequest{} }
func (m *DeleteOrderRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteOrderRequest) ProtoMessage()    {}
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{15}
}

func (m *DeleteOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOrderRequest.Unmarshal(m, b)
}
func (m *DeleteOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOrderRequest.Marshal(b, m, deterministic)
}
func (m *DeleteOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOrderRequest.Merge(m, src)
}
func (m *DeleteOrderRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteOrderRequest.Size(m)
}
func (m *DeleteOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOrderRequest proto.InternalMessageInfo

func (m *DeleteOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type DeleteOrderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOrderResponse) Reset()         { *m = DeleteOrderResponse{} }
func (m *DeleteOrderResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteOrderResponse) ProtoMessage()    {}
func (*DeleteOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{16}
}

func (m *DeleteOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOrderResponse.Unmarshal(m, b)
}
func (m *DeleteOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOrderResponse.Marshal(b, m, deterministic)
}
func (m *DeleteOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOrderResponse.Merge(m, src)
}
func (m *DeleteOrderResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteOrderResponse.Size(m)
}
func (m *DeleteOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOrderResponse proto.InternalMessageInfo

type ListOrderByEaterRequest struct {
	EaterId              string   `protobuf:"bytes,1,opt,name=eater_id,proto3" json:"eater_id,omitempty"`
	Sort                 string   `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,4,opt,name=page_size,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrderByEaterRequest) Reset()         { *m = ListOrderByEaterRequest{} }
func (m *ListOrderByEaterRequest) String() string { return proto.CompactTextString(m) }
func (*ListOrderByEaterRequest) ProtoMessage()    {}
func (*ListOrderByEaterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{17}
}

func (m *ListOrderByEaterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderByEaterRequest.Unmarshal(m, b)
}
func (m *ListOrderByEaterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderByEaterRequest.Marshal(b, m, deterministic)
}
func (m *ListOrderByEaterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderByEaterRequest.Merge(m, src)
}
func (m *ListOrderByEaterRequest) XXX_Size() int {
	return xxx_messageInfo_ListOrderByEaterRequest.Size(m)
}
func (m *ListOrderByEaterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderByEaterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderByEaterRequest proto.InternalMessageInfo

func (m *ListOrderByEaterRequest) GetEaterId() string {
	if m != nil {
		return m.EaterId
	}
	return ""
}

func (m *ListOrderByEaterRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *ListOrderByEaterRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListOrderByEaterRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListOrderByEaterResponse struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrderByEaterResponse) Reset()         { *m = ListOrderByEaterResponse{} }
func (m *ListOrderByEaterResponse) String() string { return proto.CompactTextString(m) }
func (*ListOrderByEaterResponse) ProtoMessage()    {}
func (*ListOrderByEaterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{18}
}

func (m *ListOrderByEaterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderByEaterResponse.Unmarshal(m, b)
}
func (m *ListOrderByEaterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderByEaterResponse.Marshal(b, m, deterministic)
}
func (m *ListOrderByEaterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderByEaterResponse.Merge(m, src)
}
func (m *ListOrderByEaterResponse) XXX_Size() int {
	return xxx_messageInfo_ListOrderByEaterResponse.Size(m)
}
func (m *ListOrderByEaterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderByEaterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderByEaterResponse proto.InternalMessageInfo

func (m *ListOrderByEaterResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*RestaurantInfo)(nil), "RestaurantInfo")
	proto.RegisterType((*AddressInfo)(nil), "AddressInfo")
	proto.RegisterType((*DeliveryInfo)(nil), "DeliveryInfo")
	proto.RegisterType((*PaymentInfo)(nil), "PaymentInfo")
	proto.RegisterType((*CartProduct)(nil), "CartProduct")
	proto.RegisterType((*CartItem)(nil), "CartItem")
	proto.RegisterType((*Cart)(nil), "Cart")
	proto.RegisterType((*OrderItem)(nil), "OrderItem")
	proto.RegisterType((*Order)(nil), "Order")
	proto.RegisterType((*PlaceOrderRequest)(nil), "PlaceOrderRequest")
	proto.RegisterType((*PlaceOrderResponse)(nil), "PlaceOrderResponse")
	proto.RegisterType((*UpdateOrderRequest)(nil), "UpdateOrderRequest")
	proto.RegisterType((*UpdateOrderResponse)(nil), "UpdateOrderResponse")
	proto.RegisterType((*GetOrderRequest)(nil), "GetOrderRequest")
	proto.RegisterType((*GetOrderResponse)(nil), "GetOrderResponse")
	proto.RegisterType((*DeleteOrderRequest)(nil), "DeleteOrderRequest")
	proto.RegisterType((*DeleteOrderResponse)(nil), "DeleteOrderResponse")
	proto.RegisterType((*ListOrderByEaterRequest)(nil), "ListOrderByEaterRequest")
	proto.RegisterType((*ListOrderByEaterResponse)(nil), "ListOrderByEaterResponse")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 736 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcd, 0x6e, 0xd4, 0x3c,
	0x14, 0x55, 0x3a, 0x93, 0x99, 0xc9, 0x4d, 0x7f, 0xbe, 0xcf, 0x2d, 0x10, 0x55, 0x55, 0x19, 0x59,
	0xa8, 0x2a, 0x0b, 0xd2, 0x6a, 0xba, 0x63, 0x47, 0x29, 0xaa, 0x2a, 0x21, 0xa8, 0x22, 0xb1, 0x61,
	0x33, 0x98, 0x89, 0x29, 0x16, 0x99, 0x64, 0x6a, 0x3b, 0xa0, 0x81, 0x27, 0xe0, 0x11, 0x78, 0x1e,
	0xd6, 0xbc, 0x13, 0xf2, 0x5f, 0xfe, 0x06, 0x95, 0x61, 0x15, 0xdf, 0x73, 0x6d, 0x9f, 0x7b, 0xcf,
	0xb1, 0x1d, 0x08, 0x0b, 0x9e, 0x52, 0x1e, 0x2f, 0x78, 0x21, 0x0b, 0x7c, 0x0e, 0xdb, 0x09, 0x15,
	0x92, 0x94, 0x9c, 0xe4, 0xf2, 0x2a, 0xff, 0x50, 0x20, 0x04, 0xfd, 0x9c, 0xcc, 0x69, 0xd4, 0x1b,
	0x7b, 0xc7, 0x41, 0xa2, 0xc7, 0xe8, 0x00, 0x02, 0x36, 0x27, 0x37, 0x74, 0x5a, 0xf2, 0x2c, 0xea,
	0xeb, 0x44, 0x0d, 0xe0, 0x4f, 0x10, 0x3e, 0x4b, 0x53, 0x4e, 0x85, 0xd0, 0x1b, 0x6c, 0xc3, 0x06,
	0x4b, 0x23, 0x4f, 0xcf, 0xda, 0x60, 0x69, 0xb5, 0xe1, 0x46, 0x7b, 0xc3, 0xac, 0xc8, 0x6f, 0x98,
	0x2c, 0x53, 0xc3, 0xe4, 0x25, 0x35, 0x80, 0xf6, 0x61, 0x94, 0x11, 0x69, 0x92, 0x7d, 0x9d, 0xac,
	0x62, 0xfc, 0x0e, 0x36, 0x2f, 0x68, 0xc6, 0x3e, 0x53, 0xbe, 0xd4, 0x6c, 0x47, 0x30, 0x24, 0x86,
	0x5c, 0x13, 0x84, 0x93, 0xcd, 0xb8, 0x51, 0x4c, 0xe2, 0x92, 0xaa, 0x0a, 0xc9, 0xea, 0xb6, 0xd4,
	0x18, 0xed, 0x81, 0x9f, 0x17, 0x92, 0x0a, 0xdb, 0x92, 0x09, 0xf0, 0x77, 0x0f, 0xc2, 0x6b, 0xb2,
	0x9c, 0x53, 0x2b, 0xc8, 0x7d, 0x18, 0xcc, 0xa9, 0xfc, 0x58, 0xb8, 0x9e, 0x6c, 0x84, 0x22, 0x18,
	0xce, 0x08, 0x4f, 0xa7, 0x2c, 0xb5, 0xad, 0xb9, 0x10, 0x1d, 0xc1, 0x76, 0x6a, 0x6b, 0x9c, 0x2e,
	0x38, 0x9b, 0x19, 0x56, 0x3f, 0xe9, 0xa0, 0x68, 0x0c, 0xa1, 0x2c, 0x24, 0xc9, 0xec, 0xa4, 0xbe,
	0x9e, 0xd4, 0x84, 0xf0, 0x25, 0x84, 0xcf, 0x09, 0x97, 0xd7, 0xbc, 0x48, 0xcb, 0x99, 0x5c, 0x4b,
	0xda, 0x3d, 0xf0, 0x9b, 0x9c, 0x26, 0xc0, 0xaf, 0x60, 0xa4, 0x36, 0xba, 0x92, 0x74, 0xae, 0x24,
	0x5b, 0x98, 0x0d, 0xf5, 0x56, 0x4a, 0xb2, 0x06, 0x49, 0xe2, 0x92, 0xca, 0x86, 0xdb, 0x92, 0xe4,
	0x92, 0xc9, 0xa5, 0x66, 0xf0, 0x93, 0x2a, 0xc6, 0xbf, 0x3c, 0xe8, 0xab, 0x45, 0xaa, 0x07, 0x96,
	0x0b, 0xc9, 0xcb, 0x99, 0x64, 0x45, 0x6e, 0x6b, 0x6b, 0x42, 0xe8, 0x04, 0x80, 0x57, 0x47, 0xcc,
	0x9a, 0xb4, 0x13, 0xb7, 0x4f, 0x5d, 0xd2, 0x98, 0x82, 0x1e, 0xc3, 0xc8, 0x09, 0xa5, 0x9b, 0x08,
	0x27, 0x5b, 0x71, 0xd3, 0xf3, 0xa4, 0x4a, 0xeb, 0x56, 0x8c, 0x55, 0x5a, 0x3d, 0xd5, 0x4a, 0xc3,
	0xba, 0xc4, 0x25, 0xd1, 0x43, 0xf0, 0x99, 0xa4, 0x73, 0x11, 0xf9, 0xe3, 0xde, 0x71, 0x38, 0x09,
	0x62, 0x27, 0x46, 0x62, 0x70, 0xfc, 0xd3, 0x83, 0xe0, 0xb5, 0xba, 0x17, 0x5a, 0xa1, 0xae, 0xce,
	0x87, 0x00, 0x56, 0x94, 0xda, 0xed, 0x06, 0xf2, 0xc7, 0x3b, 0xd3, 0x54, 0xaf, 0xdf, 0x56, 0xaf,
	0xf6, 0xc8, 0x6f, 0x78, 0xd4, 0x3d, 0x0e, 0x83, 0x95, 0xe3, 0xa0, 0xea, 0x98, 0x71, 0x4a, 0x24,
	0x4d, 0xa7, 0x44, 0x46, 0x43, 0x53, 0x47, 0x8d, 0xe0, 0x1f, 0x3d, 0xf0, 0x75, 0x17, 0x2b, 0x1d,
	0xec, 0xc3, 0x48, 0xcd, 0xe2, 0x75, 0xfd, 0x55, 0xdc, 0xb5, 0xb0, 0xb7, 0x6a, 0xe1, 0x01, 0x04,
	0x54, 0x57, 0xae, 0x96, 0xdb, 0xfb, 0x5f, 0x01, 0x1d, 0x83, 0xfd, 0x7f, 0x33, 0x78, 0xb0, 0xb6,
	0xc1, 0xc3, 0xbb, 0x0c, 0x1e, 0x3b, 0x83, 0x47, 0xda, 0x60, 0x88, 0x2b, 0x33, 0xad, 0xc3, 0xea,
	0x1a, 0x0b, 0x49, 0x64, 0x29, 0xa2, 0xc0, 0x5c, 0x63, 0x13, 0xa9, 0xcb, 0x6a, 0x37, 0x99, 0xda,
	0x3c, 0xe8, 0x7c, 0x07, 0xed, 0x68, 0x1f, 0x76, 0xb5, 0x57, 0xf9, 0x72, 0x91, 0xba, 0xfc, 0xa6,
	0xc9, 0xd7, 0x08, 0xfe, 0x02, 0xff, 0x5f, 0x67, 0x64, 0x46, 0x75, 0x61, 0x09, 0xbd, 0x2d, 0xa9,
	0x90, 0x2d, 0x5b, 0xbc, 0x8e, 0x2d, 0x8f, 0x60, 0xab, 0xd6, 0xac, 0xf6, 0xad, 0x0d, 0xfe, 0xdd,
	0x3c, 0x3c, 0x01, 0xd4, 0x24, 0x16, 0x8b, 0x22, 0x17, 0xea, 0x05, 0xf6, 0xf5, 0x7f, 0xc0, 0x3e,
	0x01, 0x03, 0x23, 0x58, 0x62, 0x40, 0xb5, 0xe6, 0x8d, 0x2e, 0xbd, 0x55, 0xed, 0xdd, 0x6b, 0xce,
	0x60, 0xb7, 0xb5, 0x66, 0x2d, 0xa2, 0x27, 0xb0, 0x73, 0x49, 0x65, 0x57, 0x13, 0x9d, 0x6b, 0x68,
	0xe2, 0x62, 0x7c, 0x0a, 0xff, 0xd5, 0xd3, 0xd7, 0x22, 0x38, 0x05, 0x74, 0x41, 0x33, 0x2a, 0xe9,
	0xda, 0x1c, 0xf7, 0x60, 0xb7, 0xb5, 0xc2, 0xd0, 0xe0, 0x6f, 0xf0, 0xe0, 0x25, 0x13, 0x86, 0xfb,
	0x7c, 0xf9, 0x42, 0xb9, 0xb4, 0x8e, 0x8b, 0x08, 0xfa, 0xa2, 0xe0, 0xd2, 0x3d, 0xd1, 0x6a, 0xac,
	0xb0, 0x05, 0xb9, 0x71, 0x2f, 0xb4, 0x1e, 0xab, 0x2b, 0xa6, 0xbe, 0x53, 0xc1, 0xbe, 0xba, 0x3f,
	0x41, 0x0d, 0xe0, 0xa7, 0x10, 0xad, 0x92, 0xdb, 0xfe, 0x0f, 0x61, 0xa0, 0x6b, 0x17, 0x91, 0xa7,
	0xcf, 0xbe, 0x13, 0xc0, 0xa2, 0xe7, 0xc1, 0xdb, 0x61, 0x7c, 0xa2, 0xeb, 0x79, 0x3f, 0xd0, 0x3f,
	0xfd, 0xb3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x44, 0x18, 0x67, 0x03, 0x08, 0x00, 0x00,
}
