// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rating.proto

package eater

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RestaurantRating struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EaterId              string   `protobuf:"bytes,2,opt,name=eater_id,proto3" json:"eater_id,omitempty"`
	RestaurantId         string   `protobuf:"bytes,3,opt,name=restaurant_id,proto3" json:"restaurant_id,omitempty"`
	Rating               int32    `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment              string   `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestaurantRating) Reset()         { *m = RestaurantRating{} }
func (m *RestaurantRating) String() string { return proto.CompactTextString(m) }
func (*RestaurantRating) ProtoMessage()    {}
func (*RestaurantRating) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{0}
}

func (m *RestaurantRating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestaurantRating.Unmarshal(m, b)
}
func (m *RestaurantRating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestaurantRating.Marshal(b, m, deterministic)
}
func (m *RestaurantRating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestaurantRating.Merge(m, src)
}
func (m *RestaurantRating) XXX_Size() int {
	return xxx_messageInfo_RestaurantRating.Size(m)
}
func (m *RestaurantRating) XXX_DiscardUnknown() {
	xxx_messageInfo_RestaurantRating.DiscardUnknown(m)
}

var xxx_messageInfo_RestaurantRating proto.InternalMessageInfo

func (m *RestaurantRating) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RestaurantRating) GetEaterId() string {
	if m != nil {
		return m.EaterId
	}
	return ""
}

func (m *RestaurantRating) GetRestaurantId() string {
	if m != nil {
		return m.RestaurantId
	}
	return ""
}

func (m *RestaurantRating) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *RestaurantRating) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *RestaurantRating) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *RestaurantRating) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type DeliveryRating struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EaterId              string   `protobuf:"bytes,2,opt,name=eater_id,proto3" json:"eater_id,omitempty"`
	OrderId              string   `protobuf:"bytes,3,opt,name=order_id,proto3" json:"order_id,omitempty"`
	Rating               int32    `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment              string   `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeliveryRating) Reset()         { *m = DeliveryRating{} }
func (m *DeliveryRating) String() string { return proto.CompactTextString(m) }
func (*DeliveryRating) ProtoMessage()    {}
func (*DeliveryRating) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{1}
}

func (m *DeliveryRating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliveryRating.Unmarshal(m, b)
}
func (m *DeliveryRating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliveryRating.Marshal(b, m, deterministic)
}
func (m *DeliveryRating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliveryRating.Merge(m, src)
}
func (m *DeliveryRating) XXX_Size() int {
	return xxx_messageInfo_DeliveryRating.Size(m)
}
func (m *DeliveryRating) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliveryRating.DiscardUnknown(m)
}

var xxx_messageInfo_DeliveryRating proto.InternalMessageInfo

func (m *DeliveryRating) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeliveryRating) GetEaterId() string {
	if m != nil {
		return m.EaterId
	}
	return ""
}

func (m *DeliveryRating) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *DeliveryRating) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *DeliveryRating) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *DeliveryRating) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *DeliveryRating) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type RateRestaurantRequest struct {
	EaterId              string   `protobuf:"bytes,1,opt,name=eater_id,proto3" json:"eater_id,omitempty"`
	RestaurantId         string   `protobuf:"bytes,2,opt,name=restaurant_id,proto3" json:"restaurant_id,omitempty"`
	Rating               int32    `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment              string   `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RateRestaurantRequest) Reset()         { *m = RateRestaurantRequest{} }
func (m *RateRestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*RateRestaurantRequest) ProtoMessage()    {}
func (*RateRestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{2}
}

func (m *RateRestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateRestaurantRequest.Unmarshal(m, b)
}
func (m *RateRestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateRestaurantRequest.Marshal(b, m, deterministic)
}
func (m *RateRestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateRestaurantRequest.Merge(m, src)
}
func (m *RateRestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_RateRestaurantRequest.Size(m)
}
func (m *RateRestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RateRestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RateRestaurantRequest proto.InternalMessageInfo

func (m *RateRestaurantRequest) GetEaterId() string {
	if m != nil {
		return m.EaterId
	}
	return ""
}

func (m *RateRestaurantRequest) GetRestaurantId() string {
	if m != nil {
		return m.RestaurantId
	}
	return ""
}

func (m *RateRestaurantRequest) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *RateRestaurantRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type RateRestaurantResponse struct {
	Rating               *RestaurantRating `protobuf:"bytes,1,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RateRestaurantResponse) Reset()         { *m = RateRestaurantResponse{} }
func (m *RateRestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*RateRestaurantResponse) ProtoMessage()    {}
func (*RateRestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{3}
}

func (m *RateRestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateRestaurantResponse.Unmarshal(m, b)
}
func (m *RateRestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateRestaurantResponse.Marshal(b, m, deterministic)
}
func (m *RateRestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateRestaurantResponse.Merge(m, src)
}
func (m *RateRestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_RateRestaurantResponse.Size(m)
}
func (m *RateRestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RateRestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RateRestaurantResponse proto.InternalMessageInfo

func (m *RateRestaurantResponse) GetRating() *RestaurantRating {
	if m != nil {
		return m.Rating
	}
	return nil
}

type UpdateRestaurantRatingRequest struct {
	RatingId             string   `protobuf:"bytes,1,opt,name=rating_id,proto3" json:"rating_id,omitempty"`
	Rating               int32    `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment              string   `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRestaurantRatingRequest) Reset()         { *m = UpdateRestaurantRatingRequest{} }
func (m *UpdateRestaurantRatingRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRestaurantRatingRequest) ProtoMessage()    {}
func (*UpdateRestaurantRatingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{4}
}

func (m *UpdateRestaurantRatingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRestaurantRatingRequest.Unmarshal(m, b)
}
func (m *UpdateRestaurantRatingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRestaurantRatingRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRestaurantRatingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRestaurantRatingRequest.Merge(m, src)
}
func (m *UpdateRestaurantRatingRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRestaurantRatingRequest.Size(m)
}
func (m *UpdateRestaurantRatingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRestaurantRatingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRestaurantRatingRequest proto.InternalMessageInfo

func (m *UpdateRestaurantRatingRequest) GetRatingId() string {
	if m != nil {
		return m.RatingId
	}
	return ""
}

func (m *UpdateRestaurantRatingRequest) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *UpdateRestaurantRatingRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type UpdateRestaurantRatingResponse struct {
	Rating               *RestaurantRating `protobuf:"bytes,1,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateRestaurantRatingResponse) Reset()         { *m = UpdateRestaurantRatingResponse{} }
func (m *UpdateRestaurantRatingResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRestaurantRatingResponse) ProtoMessage()    {}
func (*UpdateRestaurantRatingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{5}
}

func (m *UpdateRestaurantRatingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRestaurantRatingResponse.Unmarshal(m, b)
}
func (m *UpdateRestaurantRatingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRestaurantRatingResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRestaurantRatingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRestaurantRatingResponse.Merge(m, src)
}
func (m *UpdateRestaurantRatingResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRestaurantRatingResponse.Size(m)
}
func (m *UpdateRestaurantRatingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRestaurantRatingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRestaurantRatingResponse proto.InternalMessageInfo

func (m *UpdateRestaurantRatingResponse) GetRating() *RestaurantRating {
	if m != nil {
		return m.Rating
	}
	return nil
}

type ListRestaurantRatingByEaterRequest struct {
	EaterId              string   `protobuf:"bytes,1,opt,name=eater_id,proto3" json:"eater_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRestaurantRatingByEaterRequest) Reset()         { *m = ListRestaurantRatingByEaterRequest{} }
func (m *ListRestaurantRatingByEaterRequest) String() string { return proto.CompactTextString(m) }
func (*ListRestaurantRatingByEaterRequest) ProtoMessage()    {}
func (*ListRestaurantRatingByEaterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{6}
}

func (m *ListRestaurantRatingByEaterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRestaurantRatingByEaterRequest.Unmarshal(m, b)
}
func (m *ListRestaurantRatingByEaterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRestaurantRatingByEaterRequest.Marshal(b, m, deterministic)
}
func (m *ListRestaurantRatingByEaterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRestaurantRatingByEaterRequest.Merge(m, src)
}
func (m *ListRestaurantRatingByEaterRequest) XXX_Size() int {
	return xxx_messageInfo_ListRestaurantRatingByEaterRequest.Size(m)
}
func (m *ListRestaurantRatingByEaterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRestaurantRatingByEaterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRestaurantRatingByEaterRequest proto.InternalMessageInfo

func (m *ListRestaurantRatingByEaterRequest) GetEaterId() string {
	if m != nil {
		return m.EaterId
	}
	return ""
}

type ListRestaurantRatingByEaterResponse struct {
	Ratings              []*RestaurantRating `protobuf:"bytes,1,rep,name=ratings,proto3" json:"ratings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListRestaurantRatingByEaterResponse) Reset()         { *m = ListRestaurantRatingByEaterResponse{} }
func (m *ListRestaurantRatingByEaterResponse) String() string { return proto.CompactTextString(m) }
func (*ListRestaurantRatingByEaterResponse) ProtoMessage()    {}
func (*ListRestaurantRatingByEaterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{7}
}

func (m *ListRestaurantRatingByEaterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRestaurantRatingByEaterResponse.Unmarshal(m, b)
}
func (m *ListRestaurantRatingByEaterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRestaurantRatingByEaterResponse.Marshal(b, m, deterministic)
}
func (m *ListRestaurantRatingByEaterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRestaurantRatingByEaterResponse.Merge(m, src)
}
func (m *ListRestaurantRatingByEaterResponse) XXX_Size() int {
	return xxx_messageInfo_ListRestaurantRatingByEaterResponse.Size(m)
}
func (m *ListRestaurantRatingByEaterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRestaurantRatingByEaterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRestaurantRatingByEaterResponse proto.InternalMessageInfo

func (m *ListRestaurantRatingByEaterResponse) GetRatings() []*RestaurantRating {
	if m != nil {
		return m.Ratings
	}
	return nil
}

type RateDeliveryRequest struct {
	EaterId              string   `protobuf:"bytes,1,opt,name=eater_id,proto3" json:"eater_id,omitempty"`
	OrderId              string   `protobuf:"bytes,2,opt,name=order_id,proto3" json:"order_id,omitempty"`
	Rating               int32    `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment              string   `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RateDeliveryRequest) Reset()         { *m = RateDeliveryRequest{} }
func (m *RateDeliveryRequest) String() string { return proto.CompactTextString(m) }
func (*RateDeliveryRequest) ProtoMessage()    {}
func (*RateDeliveryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{8}
}

func (m *RateDeliveryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateDeliveryRequest.Unmarshal(m, b)
}
func (m *RateDeliveryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateDeliveryRequest.Marshal(b, m, deterministic)
}
func (m *RateDeliveryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateDeliveryRequest.Merge(m, src)
}
func (m *RateDeliveryRequest) XXX_Size() int {
	return xxx_messageInfo_RateDeliveryRequest.Size(m)
}
func (m *RateDeliveryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RateDeliveryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RateDeliveryRequest proto.InternalMessageInfo

func (m *RateDeliveryRequest) GetEaterId() string {
	if m != nil {
		return m.EaterId
	}
	return ""
}

func (m *RateDeliveryRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *RateDeliveryRequest) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *RateDeliveryRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type RateDeliveryResponse struct {
	Rating               *DeliveryRating `protobuf:"bytes,1,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RateDeliveryResponse) Reset()         { *m = RateDeliveryResponse{} }
func (m *RateDeliveryResponse) String() string { return proto.CompactTextString(m) }
func (*RateDeliveryResponse) ProtoMessage()    {}
func (*RateDeliveryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{9}
}

func (m *RateDeliveryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateDeliveryResponse.Unmarshal(m, b)
}
func (m *RateDeliveryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateDeliveryResponse.Marshal(b, m, deterministic)
}
func (m *RateDeliveryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateDeliveryResponse.Merge(m, src)
}
func (m *RateDeliveryResponse) XXX_Size() int {
	return xxx_messageInfo_RateDeliveryResponse.Size(m)
}
func (m *RateDeliveryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RateDeliveryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RateDeliveryResponse proto.InternalMessageInfo

func (m *RateDeliveryResponse) GetRating() *DeliveryRating {
	if m != nil {
		return m.Rating
	}
	return nil
}

type UpdateDeliveryRatingRequest struct {
	RatingId             string   `protobuf:"bytes,1,opt,name=rating_id,proto3" json:"rating_id,omitempty"`
	Rating               int32    `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment              string   `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDeliveryRatingRequest) Reset()         { *m = UpdateDeliveryRatingRequest{} }
func (m *UpdateDeliveryRatingRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDeliveryRatingRequest) ProtoMessage()    {}
func (*UpdateDeliveryRatingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{10}
}

func (m *UpdateDeliveryRatingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeliveryRatingRequest.Unmarshal(m, b)
}
func (m *UpdateDeliveryRatingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeliveryRatingRequest.Marshal(b, m, deterministic)
}
func (m *UpdateDeliveryRatingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeliveryRatingRequest.Merge(m, src)
}
func (m *UpdateDeliveryRatingRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDeliveryRatingRequest.Size(m)
}
func (m *UpdateDeliveryRatingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeliveryRatingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeliveryRatingRequest proto.InternalMessageInfo

func (m *UpdateDeliveryRatingRequest) GetRatingId() string {
	if m != nil {
		return m.RatingId
	}
	return ""
}

func (m *UpdateDeliveryRatingRequest) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *UpdateDeliveryRatingRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type UpdateDeliveryRatingResponse struct {
	Rating               *DeliveryRating `protobuf:"bytes,1,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateDeliveryRatingResponse) Reset()         { *m = UpdateDeliveryRatingResponse{} }
func (m *UpdateDeliveryRatingResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateDeliveryRatingResponse) ProtoMessage()    {}
func (*UpdateDeliveryRatingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{11}
}

func (m *UpdateDeliveryRatingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeliveryRatingResponse.Unmarshal(m, b)
}
func (m *UpdateDeliveryRatingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeliveryRatingResponse.Marshal(b, m, deterministic)
}
func (m *UpdateDeliveryRatingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeliveryRatingResponse.Merge(m, src)
}
func (m *UpdateDeliveryRatingResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateDeliveryRatingResponse.Size(m)
}
func (m *UpdateDeliveryRatingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeliveryRatingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeliveryRatingResponse proto.InternalMessageInfo

func (m *UpdateDeliveryRatingResponse) GetRating() *DeliveryRating {
	if m != nil {
		return m.Rating
	}
	return nil
}

type ListDeliveryRatingByEaterRequest struct {
	EaterId              string   `protobuf:"bytes,1,opt,name=eater_id,proto3" json:"eater_id,omitempty"`
	Sort                 string   `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int64    `protobuf:"varint,4,opt,name=page_size,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDeliveryRatingByEaterRequest) Reset()         { *m = ListDeliveryRatingByEaterRequest{} }
func (m *ListDeliveryRatingByEaterRequest) String() string { return proto.CompactTextString(m) }
func (*ListDeliveryRatingByEaterRequest) ProtoMessage()    {}
func (*ListDeliveryRatingByEaterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{12}
}

func (m *ListDeliveryRatingByEaterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDeliveryRatingByEaterRequest.Unmarshal(m, b)
}
func (m *ListDeliveryRatingByEaterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDeliveryRatingByEaterRequest.Marshal(b, m, deterministic)
}
func (m *ListDeliveryRatingByEaterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDeliveryRatingByEaterRequest.Merge(m, src)
}
func (m *ListDeliveryRatingByEaterRequest) XXX_Size() int {
	return xxx_messageInfo_ListDeliveryRatingByEaterRequest.Size(m)
}
func (m *ListDeliveryRatingByEaterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDeliveryRatingByEaterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDeliveryRatingByEaterRequest proto.InternalMessageInfo

func (m *ListDeliveryRatingByEaterRequest) GetEaterId() string {
	if m != nil {
		return m.EaterId
	}
	return ""
}

func (m *ListDeliveryRatingByEaterRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *ListDeliveryRatingByEaterRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListDeliveryRatingByEaterRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListDeliveryRatingByEaterResponse struct {
	Ratings              []*DeliveryRating `protobuf:"bytes,1,rep,name=ratings,proto3" json:"ratings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListDeliveryRatingByEaterResponse) Reset()         { *m = ListDeliveryRatingByEaterResponse{} }
func (m *ListDeliveryRatingByEaterResponse) String() string { return proto.CompactTextString(m) }
func (*ListDeliveryRatingByEaterResponse) ProtoMessage()    {}
func (*ListDeliveryRatingByEaterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{13}
}

func (m *ListDeliveryRatingByEaterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDeliveryRatingByEaterResponse.Unmarshal(m, b)
}
func (m *ListDeliveryRatingByEaterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDeliveryRatingByEaterResponse.Marshal(b, m, deterministic)
}
func (m *ListDeliveryRatingByEaterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDeliveryRatingByEaterResponse.Merge(m, src)
}
func (m *ListDeliveryRatingByEaterResponse) XXX_Size() int {
	return xxx_messageInfo_ListDeliveryRatingByEaterResponse.Size(m)
}
func (m *ListDeliveryRatingByEaterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDeliveryRatingByEaterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDeliveryRatingByEaterResponse proto.InternalMessageInfo

func (m *ListDeliveryRatingByEaterResponse) GetRatings() []*DeliveryRating {
	if m != nil {
		return m.Ratings
	}
	return nil
}

type GetDeliveryRatingByOrderRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeliveryRatingByOrderRequest) Reset()         { *m = GetDeliveryRatingByOrderRequest{} }
func (m *GetDeliveryRatingByOrderRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeliveryRatingByOrderRequest) ProtoMessage()    {}
func (*GetDeliveryRatingByOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{14}
}

func (m *GetDeliveryRatingByOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeliveryRatingByOrderRequest.Unmarshal(m, b)
}
func (m *GetDeliveryRatingByOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeliveryRatingByOrderRequest.Marshal(b, m, deterministic)
}
func (m *GetDeliveryRatingByOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeliveryRatingByOrderRequest.Merge(m, src)
}
func (m *GetDeliveryRatingByOrderRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeliveryRatingByOrderRequest.Size(m)
}
func (m *GetDeliveryRatingByOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeliveryRatingByOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeliveryRatingByOrderRequest proto.InternalMessageInfo

func (m *GetDeliveryRatingByOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type GetDeliveryRatingByOrderResponse struct {
	Rating               *DeliveryRating `protobuf:"bytes,1,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetDeliveryRatingByOrderResponse) Reset()         { *m = GetDeliveryRatingByOrderResponse{} }
func (m *GetDeliveryRatingByOrderResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeliveryRatingByOrderResponse) ProtoMessage()    {}
func (*GetDeliveryRatingByOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f98441b067dcd23a, []int{15}
}

func (m *GetDeliveryRatingByOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeliveryRatingByOrderResponse.Unmarshal(m, b)
}
func (m *GetDeliveryRatingByOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeliveryRatingByOrderResponse.Marshal(b, m, deterministic)
}
func (m *GetDeliveryRatingByOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeliveryRatingByOrderResponse.Merge(m, src)
}
func (m *GetDeliveryRatingByOrderResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeliveryRatingByOrderResponse.Size(m)
}
func (m *GetDeliveryRatingByOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeliveryRatingByOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeliveryRatingByOrderResponse proto.InternalMessageInfo

func (m *GetDeliveryRatingByOrderResponse) GetRating() *DeliveryRating {
	if m != nil {
		return m.Rating
	}
	return nil
}

func init() {
	proto.RegisterType((*RestaurantRating)(nil), "RestaurantRating")
	proto.RegisterType((*DeliveryRating)(nil), "DeliveryRating")
	proto.RegisterType((*RateRestaurantRequest)(nil), "RateRestaurantRequest")
	proto.RegisterType((*RateRestaurantResponse)(nil), "RateRestaurantResponse")
	proto.RegisterType((*UpdateRestaurantRatingRequest)(nil), "UpdateRestaurantRatingRequest")
	proto.RegisterType((*UpdateRestaurantRatingResponse)(nil), "UpdateRestaurantRatingResponse")
	proto.RegisterType((*ListRestaurantRatingByEaterRequest)(nil), "ListRestaurantRatingByEaterRequest")
	proto.RegisterType((*ListRestaurantRatingByEaterResponse)(nil), "ListRestaurantRatingByEaterResponse")
	proto.RegisterType((*RateDeliveryRequest)(nil), "RateDeliveryRequest")
	proto.RegisterType((*RateDeliveryResponse)(nil), "RateDeliveryResponse")
	proto.RegisterType((*UpdateDeliveryRatingRequest)(nil), "UpdateDeliveryRatingRequest")
	proto.RegisterType((*UpdateDeliveryRatingResponse)(nil), "UpdateDeliveryRatingResponse")
	proto.RegisterType((*ListDeliveryRatingByEaterRequest)(nil), "ListDeliveryRatingByEaterRequest")
	proto.RegisterType((*ListDeliveryRatingByEaterResponse)(nil), "ListDeliveryRatingByEaterResponse")
	proto.RegisterType((*GetDeliveryRatingByOrderRequest)(nil), "GetDeliveryRatingByOrderRequest")
	proto.RegisterType((*GetDeliveryRatingByOrderResponse)(nil), "GetDeliveryRatingByOrderResponse")
}

func init() { proto.RegisterFile("rating.proto", fileDescriptor_f98441b067dcd23a) }

var fileDescriptor_f98441b067dcd23a = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0x65, 0x92, 0x6e, 0xb3, 0xbd, 0xea, 0xaa, 0xa3, 0x2e, 0x71, 0x5d, 0xd7, 0x38, 0x0a, 0xae,
	0x08, 0x11, 0xf4, 0x55, 0x50, 0x56, 0xa5, 0x48, 0x45, 0x61, 0xc0, 0x17, 0x5f, 0x4a, 0x6c, 0x86,
	0x12, 0xb0, 0x49, 0x9c, 0x99, 0x0a, 0xf5, 0xc5, 0x17, 0xdf, 0xfc, 0x67, 0xfe, 0x00, 0x7f, 0x8f,
	0xcc, 0x4c, 0x32, 0xf9, 0x68, 0x53, 0x53, 0x41, 0xf6, 0xa9, 0x73, 0xef, 0xb9, 0x33, 0xf7, 0x9c,
	0x7b, 0x4f, 0x09, 0x5c, 0xe4, 0x91, 0x4c, 0xd2, 0x79, 0x98, 0xf3, 0x4c, 0x66, 0xe4, 0x37, 0x82,
	0x2b, 0x94, 0x09, 0x19, 0x2d, 0x79, 0x94, 0x4a, 0xaa, 0x21, 0x7c, 0x00, 0x4e, 0x12, 0xfb, 0x28,
	0x40, 0xa7, 0x23, 0xea, 0x24, 0x31, 0x3e, 0x82, 0x7d, 0x16, 0x49, 0xc6, 0xa7, 0x49, 0xec, 0x3b,
	0x3a, 0x6b, 0x63, 0x7c, 0x1f, 0x2e, 0x71, 0x7b, 0x5f, 0x15, 0xb8, 0xba, 0xa0, 0x99, 0xc4, 0x87,
	0x30, 0x34, 0x6d, 0xfd, 0x41, 0x80, 0x4e, 0xf7, 0x68, 0x11, 0x61, 0x1f, 0xbc, 0x59, 0xb6, 0x58,
	0xb0, 0x54, 0xfa, 0x7b, 0xfa, 0x5e, 0x19, 0xe2, 0x13, 0x80, 0x19, 0x57, 0x5d, 0xe2, 0x69, 0x24,
	0xfd, 0xa1, 0x06, 0x6b, 0x19, 0x85, 0x2f, 0xf3, 0xb8, 0xc4, 0x3d, 0x83, 0x57, 0x19, 0xf2, 0x0b,
	0xc1, 0xc1, 0x2b, 0xf6, 0x39, 0xf9, 0xca, 0xf8, 0xea, 0x1f, 0x64, 0x1d, 0xc1, 0x7e, 0xc6, 0x63,
	0x83, 0x19, 0x45, 0x36, 0x3e, 0x07, 0x31, 0x3f, 0x11, 0xdc, 0xa0, 0x91, 0x64, 0xb5, 0x4d, 0xb1,
	0x2f, 0x4b, 0x26, 0x64, 0x43, 0x03, 0xfa, 0xdb, 0x6a, 0x9c, 0xed, 0xab, 0x71, 0xbb, 0xd4, 0x0c,
	0x1a, 0x6a, 0xc8, 0x4b, 0x38, 0x6c, 0x93, 0x11, 0x79, 0x96, 0x0a, 0x86, 0x1f, 0xda, 0xb7, 0x14,
	0x97, 0x0b, 0x4f, 0xae, 0x86, 0x6d, 0x6f, 0x95, 0xcf, 0x93, 0x0c, 0x6e, 0x7f, 0xd0, 0x02, 0xd7,
	0x2a, 0x0a, 0x65, 0xc7, 0x30, 0x32, 0xa5, 0x95, 0xb4, 0x2a, 0x51, 0x63, 0xed, 0x74, 0xb1, 0x76,
	0x9b, 0xac, 0x27, 0x70, 0xd2, 0xd5, 0x70, 0x77, 0xf6, 0x2f, 0x80, 0xbc, 0x4d, 0x84, 0x6c, 0xe3,
	0x67, 0xab, 0xd7, 0x6a, 0xf8, 0x3d, 0x96, 0x43, 0x28, 0xdc, 0xdb, 0xfa, 0x42, 0xc1, 0xe9, 0x11,
	0x78, 0xa6, 0xa5, 0xf0, 0x51, 0xe0, 0x6e, 0x26, 0x55, 0x56, 0x90, 0xef, 0x70, 0x4d, 0x2d, 0xc6,
	0xda, 0xbe, 0x87, 0x47, 0xea, 0x3e, 0x77, 0x3a, 0x7d, 0xde, 0xd7, 0x19, 0xcf, 0xe1, 0x7a, 0x93,
	0x40, 0xa1, 0xe2, 0x41, 0x6b, 0xb2, 0x97, 0xc3, 0xe6, 0x5f, 0xd3, 0xce, 0x75, 0x01, 0xb7, 0xcc,
	0x92, 0x5a, 0xf8, 0x7f, 0xf2, 0xc4, 0x18, 0x8e, 0x37, 0xb7, 0xdb, 0x95, 0xf7, 0x0f, 0x04, 0x81,
	0x5a, 0x67, 0x13, 0xee, 0x6f, 0x07, 0x8c, 0x61, 0x20, 0x32, 0x2e, 0x8b, 0x1d, 0xe8, 0xb3, 0xca,
	0xe5, 0xd1, 0x9c, 0x69, 0xd2, 0x2e, 0xd5, 0x67, 0x35, 0x01, 0xf5, 0x3b, 0x15, 0xc9, 0x37, 0xa6,
	0xa7, 0xef, 0xd2, 0x2a, 0x41, 0xde, 0xc1, 0xdd, 0x2d, 0x2c, 0xac, 0xcd, 0x5b, 0x96, 0x5a, 0x53,
	0x65, 0x0d, 0xf5, 0x0c, 0xee, 0x8c, 0xd9, 0xda, 0x73, 0xef, 0x95, 0x41, 0x4a, 0x51, 0x37, 0x6b,
	0x06, 0x32, 0xa2, 0x3c, 0x1d, 0xbf, 0x89, 0xc9, 0x04, 0x82, 0xee, 0xdb, 0x3b, 0x4e, 0xf8, 0x6c,
	0xf4, 0xd1, 0x0b, 0x1f, 0xeb, 0x71, 0x7d, 0x1a, 0xea, 0x4f, 0xd7, 0xd3, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x49, 0xf7, 0x58, 0xcd, 0xca, 0x06, 0x00, 0x00,
}
