// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet.proto

package eater

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PaymentCardView struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EaterId              string   `protobuf:"bytes,2,opt,name=eater_id,proto3" json:"eater_id,omitempty"`
	Number               string   `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	IsVerified           bool     `protobuf:"varint,4,opt,name=is_verified,proto3" json:"is_verified,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentCardView) Reset()         { *m = PaymentCardView{} }
func (m *PaymentCardView) String() string { return proto.CompactTextString(m) }
func (*PaymentCardView) ProtoMessage()    {}
func (*PaymentCardView) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{0}
}

func (m *PaymentCardView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentCardView.Unmarshal(m, b)
}
func (m *PaymentCardView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentCardView.Marshal(b, m, deterministic)
}
func (m *PaymentCardView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentCardView.Merge(m, src)
}
func (m *PaymentCardView) XXX_Size() int {
	return xxx_messageInfo_PaymentCardView.Size(m)
}
func (m *PaymentCardView) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentCardView.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentCardView proto.InternalMessageInfo

func (m *PaymentCardView) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PaymentCardView) GetEaterId() string {
	if m != nil {
		return m.EaterId
	}
	return ""
}

func (m *PaymentCardView) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *PaymentCardView) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *PaymentCardView) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type AddPaymentCardRequest struct {
	EaterId              string   `protobuf:"bytes,1,opt,name=eater_id,json=eaterId,proto3" json:"eater_id,omitempty"`
	CardNumber           string   `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardToken            string   `protobuf:"bytes,3,opt,name=card_token,json=cardToken,proto3" json:"card_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPaymentCardRequest) Reset()         { *m = AddPaymentCardRequest{} }
func (m *AddPaymentCardRequest) String() string { return proto.CompactTextString(m) }
func (*AddPaymentCardRequest) ProtoMessage()    {}
func (*AddPaymentCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{1}
}

func (m *AddPaymentCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPaymentCardRequest.Unmarshal(m, b)
}
func (m *AddPaymentCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPaymentCardRequest.Marshal(b, m, deterministic)
}
func (m *AddPaymentCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPaymentCardRequest.Merge(m, src)
}
func (m *AddPaymentCardRequest) XXX_Size() int {
	return xxx_messageInfo_AddPaymentCardRequest.Size(m)
}
func (m *AddPaymentCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPaymentCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPaymentCardRequest proto.InternalMessageInfo

func (m *AddPaymentCardRequest) GetEaterId() string {
	if m != nil {
		return m.EaterId
	}
	return ""
}

func (m *AddPaymentCardRequest) GetCardNumber() string {
	if m != nil {
		return m.CardNumber
	}
	return ""
}

func (m *AddPaymentCardRequest) GetCardToken() string {
	if m != nil {
		return m.CardToken
	}
	return ""
}

type AddPaymentCardResponse struct {
	Card                 *PaymentCardView `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddPaymentCardResponse) Reset()         { *m = AddPaymentCardResponse{} }
func (m *AddPaymentCardResponse) String() string { return proto.CompactTextString(m) }
func (*AddPaymentCardResponse) ProtoMessage()    {}
func (*AddPaymentCardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{2}
}

func (m *AddPaymentCardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPaymentCardResponse.Unmarshal(m, b)
}
func (m *AddPaymentCardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPaymentCardResponse.Marshal(b, m, deterministic)
}
func (m *AddPaymentCardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPaymentCardResponse.Merge(m, src)
}
func (m *AddPaymentCardResponse) XXX_Size() int {
	return xxx_messageInfo_AddPaymentCardResponse.Size(m)
}
func (m *AddPaymentCardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPaymentCardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPaymentCardResponse proto.InternalMessageInfo

func (m *AddPaymentCardResponse) GetCard() *PaymentCardView {
	if m != nil {
		return m.Card
	}
	return nil
}

type DeletePaymentCardRequest struct {
	CardId               string   `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePaymentCardRequest) Reset()         { *m = DeletePaymentCardRequest{} }
func (m *DeletePaymentCardRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePaymentCardRequest) ProtoMessage()    {}
func (*DeletePaymentCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{3}
}

func (m *DeletePaymentCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePaymentCardRequest.Unmarshal(m, b)
}
func (m *DeletePaymentCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePaymentCardRequest.Marshal(b, m, deterministic)
}
func (m *DeletePaymentCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePaymentCardRequest.Merge(m, src)
}
func (m *DeletePaymentCardRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePaymentCardRequest.Size(m)
}
func (m *DeletePaymentCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePaymentCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePaymentCardRequest proto.InternalMessageInfo

func (m *DeletePaymentCardRequest) GetCardId() string {
	if m != nil {
		return m.CardId
	}
	return ""
}

type DeletePaymentCardResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePaymentCardResponse) Reset()         { *m = DeletePaymentCardResponse{} }
func (m *DeletePaymentCardResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePaymentCardResponse) ProtoMessage()    {}
func (*DeletePaymentCardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{4}
}

func (m *DeletePaymentCardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePaymentCardResponse.Unmarshal(m, b)
}
func (m *DeletePaymentCardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePaymentCardResponse.Marshal(b, m, deterministic)
}
func (m *DeletePaymentCardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePaymentCardResponse.Merge(m, src)
}
func (m *DeletePaymentCardResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePaymentCardResponse.Size(m)
}
func (m *DeletePaymentCardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePaymentCardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePaymentCardResponse proto.InternalMessageInfo

type GetPaymentCardRequest struct {
	CardId               string   `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPaymentCardRequest) Reset()         { *m = GetPaymentCardRequest{} }
func (m *GetPaymentCardRequest) String() string { return proto.CompactTextString(m) }
func (*GetPaymentCardRequest) ProtoMessage()    {}
func (*GetPaymentCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{5}
}

func (m *GetPaymentCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaymentCardRequest.Unmarshal(m, b)
}
func (m *GetPaymentCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaymentCardRequest.Marshal(b, m, deterministic)
}
func (m *GetPaymentCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaymentCardRequest.Merge(m, src)
}
func (m *GetPaymentCardRequest) XXX_Size() int {
	return xxx_messageInfo_GetPaymentCardRequest.Size(m)
}
func (m *GetPaymentCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaymentCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaymentCardRequest proto.InternalMessageInfo

func (m *GetPaymentCardRequest) GetCardId() string {
	if m != nil {
		return m.CardId
	}
	return ""
}

type GetPaymentCardResponse struct {
	Card                 *PaymentCardView `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetPaymentCardResponse) Reset()         { *m = GetPaymentCardResponse{} }
func (m *GetPaymentCardResponse) String() string { return proto.CompactTextString(m) }
func (*GetPaymentCardResponse) ProtoMessage()    {}
func (*GetPaymentCardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{6}
}

func (m *GetPaymentCardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaymentCardResponse.Unmarshal(m, b)
}
func (m *GetPaymentCardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaymentCardResponse.Marshal(b, m, deterministic)
}
func (m *GetPaymentCardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaymentCardResponse.Merge(m, src)
}
func (m *GetPaymentCardResponse) XXX_Size() int {
	return xxx_messageInfo_GetPaymentCardResponse.Size(m)
}
func (m *GetPaymentCardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaymentCardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaymentCardResponse proto.InternalMessageInfo

func (m *GetPaymentCardResponse) GetCard() *PaymentCardView {
	if m != nil {
		return m.Card
	}
	return nil
}

type ListPaymentCardByEaterRequest struct {
	EaterId              string   `protobuf:"bytes,1,opt,name=eater_id,json=eaterId,proto3" json:"eater_id,omitempty"`
	Sort                 string   `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int64    `protobuf:"varint,4,opt,name=page_size,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPaymentCardByEaterRequest) Reset()         { *m = ListPaymentCardByEaterRequest{} }
func (m *ListPaymentCardByEaterRequest) String() string { return proto.CompactTextString(m) }
func (*ListPaymentCardByEaterRequest) ProtoMessage()    {}
func (*ListPaymentCardByEaterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{7}
}

func (m *ListPaymentCardByEaterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPaymentCardByEaterRequest.Unmarshal(m, b)
}
func (m *ListPaymentCardByEaterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPaymentCardByEaterRequest.Marshal(b, m, deterministic)
}
func (m *ListPaymentCardByEaterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPaymentCardByEaterRequest.Merge(m, src)
}
func (m *ListPaymentCardByEaterRequest) XXX_Size() int {
	return xxx_messageInfo_ListPaymentCardByEaterRequest.Size(m)
}
func (m *ListPaymentCardByEaterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPaymentCardByEaterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPaymentCardByEaterRequest proto.InternalMessageInfo

func (m *ListPaymentCardByEaterRequest) GetEaterId() string {
	if m != nil {
		return m.EaterId
	}
	return ""
}

func (m *ListPaymentCardByEaterRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *ListPaymentCardByEaterRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListPaymentCardByEaterRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListPaymentCardByEaterResponse struct {
	Cards                []*PaymentCardView `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListPaymentCardByEaterResponse) Reset()         { *m = ListPaymentCardByEaterResponse{} }
func (m *ListPaymentCardByEaterResponse) String() string { return proto.CompactTextString(m) }
func (*ListPaymentCardByEaterResponse) ProtoMessage()    {}
func (*ListPaymentCardByEaterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{8}
}

func (m *ListPaymentCardByEaterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPaymentCardByEaterResponse.Unmarshal(m, b)
}
func (m *ListPaymentCardByEaterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPaymentCardByEaterResponse.Marshal(b, m, deterministic)
}
func (m *ListPaymentCardByEaterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPaymentCardByEaterResponse.Merge(m, src)
}
func (m *ListPaymentCardByEaterResponse) XXX_Size() int {
	return xxx_messageInfo_ListPaymentCardByEaterResponse.Size(m)
}
func (m *ListPaymentCardByEaterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPaymentCardByEaterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPaymentCardByEaterResponse proto.InternalMessageInfo

func (m *ListPaymentCardByEaterResponse) GetCards() []*PaymentCardView {
	if m != nil {
		return m.Cards
	}
	return nil
}

func init() {
	proto.RegisterType((*PaymentCardView)(nil), "PaymentCardView")
	proto.RegisterType((*AddPaymentCardRequest)(nil), "AddPaymentCardRequest")
	proto.RegisterType((*AddPaymentCardResponse)(nil), "AddPaymentCardResponse")
	proto.RegisterType((*DeletePaymentCardRequest)(nil), "DeletePaymentCardRequest")
	proto.RegisterType((*DeletePaymentCardResponse)(nil), "DeletePaymentCardResponse")
	proto.RegisterType((*GetPaymentCardRequest)(nil), "GetPaymentCardRequest")
	proto.RegisterType((*GetPaymentCardResponse)(nil), "GetPaymentCardResponse")
	proto.RegisterType((*ListPaymentCardByEaterRequest)(nil), "ListPaymentCardByEaterRequest")
	proto.RegisterType((*ListPaymentCardByEaterResponse)(nil), "ListPaymentCardByEaterResponse")
}

func init() { proto.RegisterFile("wallet.proto", fileDescriptor_b88fd140af4deb6f) }

var fileDescriptor_b88fd140af4deb6f = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xdf, 0x4b, 0xc3, 0x30,
	0x10, 0xc7, 0x69, 0xbb, 0x5f, 0xbd, 0x89, 0x4a, 0x60, 0xb3, 0x53, 0x37, 0x4b, 0x11, 0xd9, 0xd3,
	0x14, 0xf7, 0x3e, 0x70, 0x2a, 0x3a, 0x10, 0x91, 0x22, 0x3e, 0xf8, 0x52, 0xb2, 0xe5, 0x94, 0xe0,
	0xd6, 0xce, 0x24, 0x73, 0xcc, 0x27, 0xff, 0x0b, 0xff, 0x5d, 0x49, 0x5a, 0x66, 0x19, 0x13, 0xdc,
	0x53, 0xf3, 0xfd, 0x5e, 0xef, 0xee, 0x73, 0x97, 0xc0, 0xd6, 0x9c, 0x8e, 0xc7, 0xa8, 0x3a, 0x53,
	0x91, 0xa8, 0x24, 0xf8, 0xb6, 0x60, 0xe7, 0x81, 0x2e, 0x26, 0x18, 0xab, 0x4b, 0x2a, 0xd8, 0x13,
	0xc7, 0x39, 0xd9, 0x06, 0x9b, 0x33, 0xcf, 0xf2, 0xad, 0xb6, 0x1b, 0xda, 0x9c, 0x91, 0x7d, 0xa8,
	0x20, 0x55, 0x28, 0x22, 0xce, 0x3c, 0xdb, 0xb8, 0x4b, 0x4d, 0xea, 0x50, 0x8a, 0x67, 0x93, 0x21,
	0x0a, 0xcf, 0x31, 0x91, 0x4c, 0x11, 0x1f, 0xaa, 0x5c, 0x46, 0x1f, 0x28, 0xf8, 0x0b, 0x47, 0xe6,
	0x15, 0x7c, 0xab, 0x5d, 0x09, 0xf3, 0x16, 0x69, 0x01, 0x8c, 0x84, 0xae, 0xc3, 0x22, 0xaa, 0xbc,
	0xa2, 0xc9, 0xce, 0x39, 0x81, 0x80, 0xda, 0x05, 0x63, 0x39, 0xb6, 0x10, 0xdf, 0x67, 0x28, 0x15,
	0x69, 0xe4, 0x70, 0x52, 0xc8, 0xb2, 0xd1, 0x03, 0x46, 0x8e, 0xa0, 0x3a, 0xa2, 0x82, 0x45, 0x19,
	0x92, 0x9d, 0x15, 0xa5, 0x82, 0xdd, 0xa7, 0x58, 0x4d, 0x30, 0x2a, 0x52, 0xc9, 0x1b, 0xc6, 0x19,
	0xb2, 0xab, 0x9d, 0x47, 0x6d, 0x04, 0x3d, 0xa8, 0xaf, 0xf6, 0x94, 0xd3, 0x24, 0x96, 0x48, 0x8e,
	0xa1, 0xa0, 0x7f, 0x33, 0x0d, 0xab, 0xe7, 0xbb, 0x9d, 0x95, 0x9d, 0x85, 0x26, 0x1a, 0x74, 0xc1,
	0xbb, 0xc2, 0x31, 0x2a, 0x5c, 0x83, 0xbd, 0x07, 0x65, 0xd3, 0x7a, 0x49, 0x5d, 0xd2, 0x72, 0xc0,
	0x82, 0x03, 0x68, 0xac, 0x49, 0x4a, 0xfb, 0x06, 0x67, 0x50, 0xbb, 0x41, 0xb5, 0x49, 0xb9, 0x1e,
	0xd4, 0x57, 0x33, 0x36, 0x9a, 0xe1, 0xcb, 0x82, 0xe6, 0x1d, 0x97, 0xf9, 0x0a, 0xfd, 0xc5, 0xb5,
	0x5e, 0xf0, 0x3f, 0x2e, 0x80, 0x40, 0x41, 0x26, 0x42, 0x65, 0x9b, 0x37, 0x67, 0xed, 0x4d, 0xe9,
	0x2b, 0x9a, 0x6d, 0x3b, 0xa1, 0x39, 0x93, 0x43, 0x70, 0xf5, 0x37, 0x92, 0xfc, 0x13, 0xcd, 0xe3,
	0x70, 0xc2, 0x5f, 0x23, 0xb8, 0x85, 0xd6, 0x5f, 0x04, 0xd9, 0x28, 0x27, 0x50, 0xd4, 0xb0, 0xd2,
	0xb3, 0x7c, 0x67, 0xed, 0x2c, 0x69, 0xb8, 0xef, 0x3e, 0x97, 0x3b, 0xa7, 0x06, 0x6e, 0x58, 0x32,
	0x0f, 0xbe, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x48, 0x85, 0xe5, 0x00, 0x03, 0x00, 0x00,
}
